service: express-lambda-ts

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  app:
    handler: src/aws_lambda.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: hello
          method: get

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'
    - '!.serverless/**'
    - '!cloudformation-template-create-stack.json'

plugins:
  - serverless-plugin-typescript